# Cores e temas compartilhados
PRIMARY_COLOR = "#0A2472"  
SECONDARY_COLOR = "#3F51B5" 
BG_COLOR = "#F0F4F8" 
TEXT_COLOR = "#FFFFFF"
FONT_FAMILY = "Arial"
FONT_SIZE_LARGE = 24
FONT_SIZE_MEDIUM = 16
FONT_SIZE_SMALL = 12

# Para Pygame
BOARD_COLOR = "#FFFFFF"
LINE_COLOR = "#000000"
X_COLOR = "#FF0000"  
O_COLOR = "#0000FF"  
LINE_WIDTH = 15